version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 056374430480.dkr.ecr.ap-south-1.amazonaws.com
      # This command retrieves a token from ECR that allows Docker to authenticate to your registry
      # Note: The '$(aws ecr get-login)' command is deprecated in favor of 'aws ecr get-login-password'

  build:
    commands:
      - docker build -t flask_app .
      - docker tag flask_app:latest 056374430480.dkr.ecr.ap-south-1.amazonaws.com/flask_app:latest
      # Replace $IMAGE_REPO_NAME with your ECR repository name
      # Replace $CODEBUILD_RESOLVED_SOURCE_VERSION with a tag or commit ID

  post_build:
    commands:
      - docker push 056374430480.dkr.ecr.ap-south-1.amazonaws.com/flask_app:latest
      # Push the Docker image to ECR repository
      - ContainerName="container-name"
      - ImageURI=$(cat imageDetail.json | jq -r '.ImageURI')
      - printf '[{"name":"CONTAINER_NAME","imageUri":"IMAGE_URI"}]' > imagedefinitions.json
      - sed -i -e "s|CONTAINER_NAME|$ContainerName|g" imagedefinitions.json
      - sed -i -e "s|IMAGE_URI|$ImageURI|g" imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
